//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using XCharts;



    public class UIChartPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class UIChartPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIChartPanelData ?? new UIChartPanelData();
            // please add init code here
            CloseBtn.onClick.AddListener(() => {
                CloseSelf();
            });
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
            var chart = BarChart.GetComponent<BarChart>();
            chart.ClearData();

            if (UserDataManager.instance.MyDatas != null && UserDataManager.instance.MyDatas.Count > 0) {
                for (int i = 0; i < UserDataManager.instance.MyDatas.Count; ++i) {
                    var temp = UserDataManager.instance.MyDatas[i];
                    chart.AddXAxisData(temp.date);
                    chart.AddData(0, temp.result9);
                }
            }
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
