//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIChartPanel
    {
        
        public const string NAME = "UIChartPanel";
        
        [SerializeField()]
        public RectTransform BarChart;
        
        [SerializeField()]
        public Button CloseBtn;
        
        private UIChartPanelData mPrivateData = null;
        
        public UIChartPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIChartPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BarChart = null;
            CloseBtn = null;
            mData = null;
        }
    }
}
