//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;


    public class UITipsPanelData : QFramework.UIPanelData
    {
        public string contentString;
    }

    public partial class UITipsPanel : QFramework.UIPanel
    {

        protected override void ProcessMsg( int eventId, QFramework.QMsg msg ) {
            throw new System.NotImplementedException();
        }

        protected override void OnOpen( QFramework.IUIData uiData ) {
            mData = uiData as UITipsPanelData ?? new UITipsPanelData();

            Tips.gameObject.transform.localPosition = Vector3.zero;

            Content.text = mData.contentString;

            AnimSystem.StopAnim( Tips.gameObject );
            AnimSystem.UguiMove( Tips.gameObject, new Vector3( 0, 0, 0 ), new Vector3( 0, 60, 0 ), 1.5f, callBack: _ => {
                CloseSelf();
            } );

        }

        protected override void OnClose() {
        }
    }
}
