//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIUserDataPanel
    {
        
        public const string NAME = "UIUserDataPanel";
        
        [SerializeField()]
        public Button BtnClose;
        
        [SerializeField()]
        public Button BtnClear;
        
        [SerializeField()]
        public Button BtnSeData;
        
        [SerializeField()]
        public Button BtnDeData;
        
        [SerializeField()]
        public InputField InputField;
        
        private UIUserDataPanelData mPrivateData = null;
        
        public UIUserDataPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIUserDataPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            BtnClose = null;
            BtnClear = null;
            BtnSeData = null;
            BtnDeData = null;
            InputField = null;
            mData = null;
        }
    }
}
